# This configuration sets up DNS traffic monitoring through DNStap unix socket;
# and logging to a remote DNSTap server with TLS enabled.
#
# As prerequisites, we assume you have 
# - a DNS server which supports DNSTap (unbound, bind, powerdns, etc) for more informations about dnstap, 
#   read the following page: https://dmachard.github.io/posts/0001-dnstap-testing/
# - a remote DNSTap collector with TLS support

# If turned on, debug messages are printed in the standard output
global:
  trace:
    verbose: true

pipelines:
  # Read DNSTap stream from a UNIX socket
  - name: powerdns
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6001

    # Routes DNS messages from the Unix socket to TLS tap destination
    routing-policy:
      forward: [ outputfile-slowresponses, loki ]

  - name: outputfile-slowresponses
    logfile:
      file-path: "/var/dnscollector/dnstap-slow.log"
      mode: flat-json
  
  - name: loki
    lokiclient:
      server-url: "http://loki:3100/loki/api/v1/push"
      job-name: "dnscollector"